name: Purge jsDelivr logo cache

on:
  push:
    branches:
      - main
    paths:
      - "logos/**"

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge jsDelivr logos cache
        run: |
          echo "Purging jsDelivr cache for logos..."
          curl -s https://purge.jsdelivr.net/gh/M-GOK/Bist-Logolar@main/logos/*
